name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  build_optimize_deploy:
    runs-on: ubuntu-latest
    environment: cf

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Rust + target wasm32
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      # 3. Install wasm-pack
      - name: Install wasm-pack
        run: cargo install wasm-pack --locked

      # 4. Install wasm-opt (via Cargo)
      - name: Install wasm-opt
        run: cargo install wasm-opt --locked

      - name: Install worker-build
        run: cargo install worker-build --locked

      - name: Build release untuk Cloudflare Worker
        run: worker-build --release


      # 6. Cek dan Optimasi WASM
      - name: Cek dan Optimasi WASM
        run: |
          echo "📦 Mengecek versi wasm-opt..."
          wasm-opt --version

          INPUT="pkg/index_bg.wasm"
          if [ -f "$INPUT" ]; then
            echo "🚀 Optimizing $INPUT..."
            wasm-opt "$INPUT" --enable-bulk-memory -Oz -o "$INPUT"

          else
            echo "❌ File $INPUT tidak ditemukan!"
            exit 1
          fi

      # 7. Deploy ke Cloudflare Worker
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
